[project]
name = "ipc"
version = "0.1.0"
description = "Script to start firmware on the Cortex M4 and listen for IPC messages."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyserial>=3.5",
]
