{
 "title": "OBDADS",
 "description": "Grafana dashboard to display OBDADS insights and data.",
 "time": { "from": "2025-03-31T21:28:23.000Z", "to": "2025-03-31T21:56:42.000Z" },
 "panels": [
  {
   "title": "Engine Speed",
   "type": "stat",
   "description": "Current real-time engine speed from OBD.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_speed AS REAL) AS engine_speed\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_speed AS REAL) AS engine_speed\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vehicle Speed",
   "type": "stat",
   "description": "Current real-time vehicle speed from OBD.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(vehicle_speed AS REAL) AS vehicle_speed\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(vehicle_speed AS REAL) AS vehicle_speed\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Engine Load",
   "type": "stat",
   "description": "Current real-time engine load from OBD.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_load AS REAL) AS engine_load\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_load AS REAL) AS engine_load\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Throttle Position",
   "type": "stat",
   "description": "Current real-time throttle position from OBD.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(throttle_pos AS REAL) AS throttle_pos\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(throttle_pos AS REAL) AS throttle_pos\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "MIL Distance",
   "type": "stat",
   "description": "Current real-time distance travelled with malfunction lamp indicator turned on from OBD.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(mil_distance AS REAL) AS mil_distance\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(mil_distance AS REAL) AS mil_distance\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "O2 Sensor #1",
   "type": "stat",
   "description": "Current real-time oxygen sensor information from OBD.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor1_volt AS REAL) AS Voltage\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor1_volt AS REAL) AS Voltage\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor1_curr AS REAL) AS Current\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor1_curr AS REAL) AS Current\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "O2 Sensor #2",
   "type": "stat",
   "description": "Current real-time oxygen sensor information from OBD.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor2_volt AS REAL) AS Voltage\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor2_volt AS REAL) AS Voltage\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor2_curr AS REAL) AS Current\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(oxy_sensor2_curr AS REAL) AS Current\nFROM\n  OBD_DATA\nORDER BY\n  time DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Engine Speed Over Time",
   "type": "timeseries",
   "description": "Real-time OBD data about the engine speed over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_speed AS REAL) AS engine_speed\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_speed AS REAL) AS engine_speed\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Axis Rotation Speed Over Time",
   "type": "timeseries",
   "description": "Real-time sensor data from the IMU about the axis rotation speed.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(gx AS REAL) AS gx,\n  CAST(gy AS REAL) AS gy,\n  CAST(gz AS REAL) AS gz\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(gx AS REAL) AS gx,\n  CAST(gy AS REAL) AS gy,\n  CAST(gz AS REAL) AS gz\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vehicle Speed Over Time",
   "type": "timeseries",
   "description": "Real-time OBD data about the vehicle speed over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(vehicle_speed AS REAL) AS vehicle_speed\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(vehicle_speed AS REAL) AS vehicle_speed\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Axis Acceleration Over Time",
   "type": "timeseries",
   "description": "Real-time sensor data from the IMU about the axis accelerations.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(ax AS REAL) AS ax,\n  CAST(ay AS REAL) AS ay,\n  CAST(az AS REAL) AS az\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(ax AS REAL) AS ax,\n  CAST(ay AS REAL) AS ay,\n  CAST(az AS REAL) AS az\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Engine Load Over Time",
   "type": "timeseries",
   "description": "Real-time OBD data about the engine load over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_load AS REAL) AS engine_load\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(engine_load AS REAL) AS engine_load\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature Over Time",
   "type": "timeseries",
   "description": "Real-time sensor data from the IMU about the ambient device temperature.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(temp AS REAL) AS temp\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(temp AS REAL) AS temp\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Throttle Position Over Time",
   "type": "timeseries",
   "description": "Real-time OBD data about the throttle position over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(throttle_pos AS REAL) AS throttle_pos\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(throttle_pos AS REAL) AS throttle_pos\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "MIL Distance Over Time",
   "type": "timeseries",
   "description": "Real-time OBD data about the MIL distance over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(mil_distance AS REAL) AS mil_distance\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', timestamp) AS time,\n  CAST(mil_distance AS REAL) AS mil_distance\nFROM\n  OBD_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}