{
 "title": "Mobile OBDADS",
 "time": { "from": "2025-04-08T15:14:27.947Z", "to": "2025-04-08T21:14:27.947Z" },
 "panels": [
  {
   "title": "Throttle Position",
   "type": "stat",
   "description": "Current real-time throttle position from OBD.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time) AS time,\n  CAST(throttle_position AS REAL) AS throttle_pos\nFROM\n  OBD_DATA\nORDER BY\n  time DESC;",
     "rawQueryText": "SELECT\n  strftime('%s', time) AS time,\n  CAST(throttle_position AS REAL) AS throttle_pos\nFROM\n  OBD_DATA\nORDER BY\n  time DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Engine Load",
   "type": "stat",
   "description": "Current real-time engine load from OBD.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time) AS time,\n  CAST(engine_load AS REAL) AS engine_load\nFROM\n  OBD_DATA\nORDER BY\n  time DESC;",
     "rawQueryText": "SELECT\n  strftime('%s', time) AS time,\n  CAST(engine_load AS REAL) AS engine_load\nFROM\n  OBD_DATA\nORDER BY\n  time DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Real-time sensor data from the IMU about the ambient device temperature.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time) AS time,\n  CAST(temp AS REAL) AS temp\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "rawQueryText": "SELECT\n  strftime('%s', time) AS time,\n  CAST(temp AS REAL) AS temp\nFROM\n  IMU_DATA\nORDER BY\n  time;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "text",
   "description": "Alerts from the machine learning module regarding health and performance anomalies.",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 3 },
   "options": {
    "content": "# Monitoring\nHere is where the ML alerts go."
   }
  }
 ]
}