# This is a basic workflow to help you get started with Actions

name: ISSUE-TO-BACKLOG

# Controls when the workflow will run
on:
  # Triggers the workflow when an issue is created
  issues:
    types:
      - opened
      - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Uses GITHUB_TOKEN to add a label to an issue
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "Backlog"
